nginx:
  image: nginx:latest
  ports:
    - '80:80'
  volumes:
    - /tmp/nginx:/etc/nginx/conf.d
    - ./django-example/static:/var/www/static

dockergen:
  image: jwilder/docker-gen:latest
  links:
    - nginx
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - ./extra:/etc/docker-gen/templates
    - /etc/nginx/certs
  tty: true
  command: >
    -watch
    -only-exposed
    -notify-sighup dockerdjango_nginx_1
    /etc/docker-gen/templates/nginx.tmpl
    /etc/nginx/conf.d/default.conf

memcached:
  image: atbaker/memcached-verbose

postgres:
  image: postgres:9.3

django:
  build: .
  links:
    - memcached
    - postgres
  expose:
    - '8000'
  volumes:
    - .:/usr/src/app
  environment:
    VIRTUAL_HOST: 5.9.69.226
