nginx:
  image: jwilder/nginx-proxy
  links:
    - django
  ports:
    - '80:80'
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

django:
  build: .
  links:
    - postgres
    - memcached
  expose:
    - '8000'
  # ports:
  #   - '8000:8000'
  volumes:
    - .:/usr/src/app
  environment:
    VIRTUAL_HOST: 5.9.69.226

postgres:
  image: postgres:9.3
  # environment:
  #   POSTGRES_PASSWORD: p01f0102

memcached:
  image: atbaker/memcached-verbose
